export const initialStateValue = {
    users: [
      {
        id: "1",
        name: "Alexa",
        login: "Alexa",
        password: "1231233",
        role: "modérateur",
      },
      {
        id: "2",
        name: "Jeremy",
        login: "Jeremy",
        password: "1231233",
        role: "administrateur",
      },
      {
        id: "3",
        name: "404",
        login: "404",
        password: "1231233",
        role: "membre",
      },
      {
        id: "4",
        name: "John",
        login: "John",
        password: "1231233",
        role: "membre",
      },
      {
        id: "5",
        name: "Sophie",
        login: "Sophie",
        password: "password123",
        role: "modérateur",
      },
      {
        id: "6",
        name: "Bob",
        login: "Bob123",
        password: "qwerty123",
        role: "administrateur",
      },
      {
        id: "7",
        name: "Eva",
        login: "Eva87",
        password: "evapass",
        role: "membre",
      },
      {
        id: "8",
        name: "Mark",
        login: "MarkyMark",
        password: "markpass",
        role: "membre",
      },
      {
        id: "9",
        name: "Quackity",
        login: "Quackity",
        password: "Q",
        role: "membre",
      },
    ],
    documents : [
      {
        code_document: "1",
        nom_document: "Not found",
        etat_document: "1",
        nom_theme: "Computer science",
        login: "404",
      },
      {
        code_document: "2",
        nom_document: "Introduction to Programming",
        etat_document: "2",
        nom_theme: "Computer science",
        login: "Alexa",
      },
      {
        code_document: "3",
        nom_document: "Web Development Basics",
        etat_document: "1",
        nom_theme: "Web Development",
        login: "Quackity",
      },
      {
        code_document: "4",
        nom_document: "Data Structures and Algorithms",
        etat_document: "1",
        nom_theme: "Computer science",
        login: "John",
      },
      {
        code_document: "5",
        nom_document: "Artificial Intelligence Overview",
        etat_document: "2",
        nom_theme: "Artificial Intelligence",
        login: "Sophie",
      },
      {
        code_document: "6",
        nom_document: "Machine Learning Fundamentals",
        etat_document: "1",
        nom_theme: "Artificial Intelligence",
        login: "Sophie",
      },
      {
        code_document: "7",
        nom_document: "JavaScript Basics",
        etat_document: "2",
        nom_theme: "Web Development",
        login: "Alexa",
      },
      {
        code_document: "8",
        nom_document: "Database Management",
        etat_document: "1",
        nom_theme: "Database Systems",
        login: "John",
      },
      {
        code_document: "9",
        nom_document: "Network Security",
        etat_document: "1",
        nom_theme: "Cybersecurity",
        login: "Mark",
      },
      {
        code_document: "10",
        nom_document: "Mobile App Development",
        etat_document: "2",
        nom_theme: "Mobile Development",
        login: "Mark",
      }
  ],
  commentaires : [
    {
      code_commentaire: "1",
      date_commentaire: new Date("2023-01-01"),
      texte_commentaire: "Intéressant",
      etat_commentaire: "1",
      code_document: "1",
      login: "John",
    },
    {
      code_commentaire: "2",
      date_commentaire: new Date("2023-02-15"),
      texte_commentaire: "Très utile!",
      etat_commentaire: "2",
      code_document: "2",
      login: "Alexa",
    },
    {
      code_commentaire: "3",
      date_commentaire: new Date("2023-03-10"),
      texte_commentaire: "Bonne explication",
      etat_commentaire: "1",
      code_document: "3",
      login: "Quackity",
    },
    {
      code_commentaire: "4",
      date_commentaire: new Date("2023-04-05"),
      texte_commentaire: "J'aurais aimé plus d'exemples",
      etat_commentaire: "1",
      code_document: "1",
      login: "Sophie",
    },
    {
      code_commentaire: "5",
      date_commentaire: new Date("2023-05-05"),
      texte_commentaire: "Très informatif",
      etat_commentaire: "1",
      code_document: "3",
      login: "Sophie",
    },
  ],
    connectedUser: null,
  };